### PR TITLE
Callbacks

### PR DESCRIPTION
**Pull request by a2ron**
Bash scripts linked to Alexa interaction events as callback.

### CODE REVIEW

**Comment by ENT8R** [comment]
What is the intention behind this? I saw some code with GPIO's which presupposes that the user who uses the SDK will have to have the necessary hardware...
Is this really useful for all possible users of this SDK or is this only a change which makes sense for a single usecase?

**Comment by a2ron** [comment]
Well, user can design callback scripts for Alexa interaction events. As you have seen, in my case I have developed a script to manage the 15th GPIO in order to switch on/off a LED.

To delete this "default" behaviour or use case, we could set blank the scripts if you are interested in this feature.

Hope you find it worthy. Thanks!

**Comment by a2ron** [comment]
@ENT8R right, docu would be fine.  Where do you consider I could add it?

**Comment by ENT8R** [comment]
Either in the wiki or in the readme... I don't know what is preferred by the developers and maintainers of this repo...

**Comment by celinval** [comment]
Hi @a2ron,

That's a cool idea! That said, our process is to make changes internally and run all test before pushing releasing it to git hub. I have added your callback idea to our internal tracking system to be assessed and prioritized.

Thanks,

**Pull request closed without merging**
